function plot_figure10( ...
    B_array, ...
    hw_meV, ...
    alpha12_store, ...
    alpha23_store, ...
    alpha13_store, ...
    F_field, ...
    Nd_sheet)

    %% =========================================================
    %% DEFAULT ARGUMENTS
    %% =========================================================

    if nargin < 6
        F_field = 0;
    end

    if nargin < 7
        Nd_sheet = 0;
    end

    %% =========================================================
    %% CHECK DIMENSIONS
    %% =========================================================

    if size(alpha12_store,1) ~= length(B_array)
        error('alpha12_store size mismatch');
    end

    if size(alpha23_store,1) ~= length(B_array)
        error('alpha23_store size mismatch');
    end

    if size(alpha13_store,1) ~= length(B_array)
        error('alpha13_store size mismatch');
    end

    %% =========================================================
    %% PLOT STYLES
    %% =========================================================

    styles = {'-','--',':'};

    colors = {'b','k','r'};

    %% =========================================================
    %% LABELS
    %% =========================================================

    labels = cell(length(B_array),1);

    for i = 1:length(B_array)

        labels{i} = sprintf( ...
            'B = %.0f T', ...
            B_array(i));

    end

    %% =========================================================
    %% FIGURE
    %% =========================================================

    figure( ...
        'Color','w', ...
        'Position',[100 50 800 900]);

    %% =========================================================
    %% SUBPLOT a) alpha12
    %% =========================================================

    subplot(3,1,1);

    hold on;
    box on;
    grid on;

    for s = 1:length(B_array)

        plot( ...
            hw_meV, ...
            alpha12_store(s,:), ...
            'Color', colors{1}, ...
            'LineStyle', styles{s}, ...
            'LineWidth', 2.5, ...
            'DisplayName', labels{s});

    end

    set(gca, ...
        'XMinorGrid','on', ...
        'YMinorGrid','on', ...
        'GridLineStyle','--');

    xlim([0 300]);

    ylabel( ...
        'Total optical absorption (\alpha_{12}) (cm^{-1})', ...
        'FontWeight','bold');

    legend('Location','northeast');

    text( ...
        10, ...
        max(alpha12_store(:))*0.85, ...
        'a) \alpha_{12}', ...
        'FontSize',12, ...
        'FontWeight','bold');

    %% =========================================================
    %% SUBPLOT b) alpha23
    %% =========================================================

    subplot(3,1,2);

    hold on;
    box on;
    grid on;

    for s = 1:length(B_array)

        plot( ...
            hw_meV, ...
            alpha23_store(s,:), ...
            'Color', colors{2}, ...
            'LineStyle', styles{s}, ...
            'LineWidth', 2.5, ...
            'DisplayName', labels{s});

    end

    set(gca, ...
        'XMinorGrid','on', ...
        'YMinorGrid','on', ...
        'GridLineStyle','--');

    xlim([0 300]);

    ylabel( ...
        'Total optical absorption (\alpha_{23}) (cm^{-1})', ...
        'FontWeight','bold');

    legend('Location','northeast');

    text( ...
        10, ...
        max(alpha23_store(:))*0.85, ...
        'b) \alpha_{23}', ...
        'FontSize',12, ...
        'FontWeight','bold');

    %% =========================================================
    %% SUBPLOT c) alpha13
    %% =========================================================

    subplot(3,1,3);

    hold on;
    box on;
    grid on;

    for s = 1:length(B_array)

        plot( ...
            hw_meV, ...
            alpha13_store(s,:), ...
            'Color', colors{3}, ...
            'LineStyle', styles{s}, ...
            'LineWidth', 2.5, ...
            'DisplayName', labels{s});

    end

    set(gca, ...
        'XMinorGrid','on', ...
        'YMinorGrid','on', ...
        'GridLineStyle','--');

    xlim([0 300]);

    xlabel( ...
        'Photon energy (meV)', ...
        'FontWeight','bold', ...
        'FontSize',12);

    ylabel( ...
        'Total optical absorption (\alpha_{13}) (cm^{-1})', ...
        'FontWeight','bold');

    legend('Location','northeast');

    text( ...
        10, ...
        max(alpha13_store(:))*0.85, ...
        'c) \alpha_{13}', ...
        'FontSize',12, ...
        'FontWeight','bold');

    %% =========================================================
    %% GLOBAL TITLE
    %% =========================================================

    sgtitle( ...
        'Variation of \alpha_{12}, \alpha_{23}, and \alpha_{13} as a function of incident photon energy', ...
        'FontWeight','bold', ...
        'FontSize',14);

    %% =========================================================
    %% EXTRA INFORMATION
    %% =========================================================

    annotation( ...
        'textbox', ...
        [0.13 0.95 0.3 0.03], ...
        'String', sprintf('F = %.1f kV cm^{-1}', F_field/1e5), ...
        'EdgeColor','none', ...
        'FontWeight','bold');

    annotation( ...
        'textbox', ...
        [0.55 0.95 0.3 0.03], ...
        'String', sprintf('N_d = %.1e m^{-2}', Nd_sheet), ...
        'EdgeColor','none', ...
        'FontWeight','bold');

end